//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageHeaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageHeaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM_mvc.Resources.PageHeaders", typeof(PageHeaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجابات السؤال.
        /// </summary>
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل الإتصالات.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الإتصال.
        /// </summary>
        public static string CallInformation {
            get {
                return ResourceManager.GetString("CallInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري الإتصال.
        /// </summary>
        public static string Calling {
            get {
                return ResourceManager.GetString("Calling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل العملاء.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العميل.
        /// </summary>
        public static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنتهى الإتصال.
        /// </summary>
        public static string EndCall {
            get {
                return ResourceManager.GetString("EndCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسالة جماعية.
        /// </summary>
        public static string GroupMessage {
            get {
                return ResourceManager.GetString("GroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسائل.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسائل الإلكترونية.
        /// </summary>
        public static string MessageEmail {
            get {
                return ResourceManager.GetString("MessageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظائف.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسالة إلكترونية.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجلسات.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المستخدم.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
